<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2025/blob/main/Lab01/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals

### Data types

In [ ]:
a = 5
print(type(a))

: 

In [2]:
a = 5.0
print(type(a))

<class 'float'>


In [3]:
a = '5'
print(type(a))

<class 'str'>


In [4]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [4]:
a_list = [1, 2, 2, 4.0, '5']
print(a_list)
print(type(a_list))

[1, 2, 2, 4.0, '5']
<class 'list'>


In [6]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{1, 2, 3.0, '5'}
<class 'set'>
{1, 2, 3, 4}


In [7]:
a_dict = {
    1: 'unu',
    'doi': 2,
    3.0: a_set
}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [8]:
def add_two_values(a, b):
    return a + b

add_two_values(5, 6)

11

In [9]:
def multiply(a: float, b: float) -> float:
    return a * b

multiply(4.0, 5.0)

20.0

In [10]:
multiply("AB", 2)

'ABAB'

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [5]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [12]:
%pip install timed-decorator

In [6]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [11]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([ 1.31959832, -3.28108552,  3.95474857, -2.54724475, -3.03760966,
       -0.81272523,  0.18947427,  2.83540592,  4.45139426,  1.49839905,
        1.35232865, -4.72354575, -1.58645112,  3.23625384, -1.33332183,
        2.4791122 , -2.88279405,  0.73842133, -2.59650477,  2.03042572,
        0.81950189,  4.84927605,  4.77900228, -1.9856014 ,  0.79927518,
        1.70532992,  0.88714188,  5.26292673,  5.01258226, -4.83784941,
       -2.68703327,  3.03869336, -3.0548129 , -4.86899209, -1.40724236,
        2.40833129,  3.20920571,  4.08134772,  3.08195056,  2.03898907,
       -3.67815039,  3.63453305,  2.27328615, -1.42691841,  0.47137745,
       -1.11906134, -4.10927502,  5.2128672 ,  4.40876392,  3.62970815])

In [15]:
x > 0

array([False,  True, False,  True,  True,  True, False,  True, False,
       False, False,  True, False, False,  True,  True, False, False,
       False, False,  True,  True,  True, False,  True, False, False,
        True, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False, False, False,
       False,  True, False,  True,  True])

In [16]:
x[x > 0]

array([3.55174233, 0.63476826, 1.32473059, 3.25703386, 0.56524522,
       4.98782961, 2.05677049, 0.07322086, 4.25927931, 3.96061448,
       1.87208983, 5.1911797 , 2.74462889, 1.40324877, 1.47291849,
       4.53722535, 0.61056549, 0.49667307, 1.00205239, 0.90775139,
       2.1425354 , 3.00139925, 0.08148065])

In [15]:
list(x)

[np.float64(1.3195983162411),
 np.float64(-3.2810855249013247),
 np.float64(3.9547485684510537),
 np.float64(-2.5472447491542494),
 np.float64(-3.0376096613338834),
 np.float64(-0.812725228148258),
 np.float64(0.18947427229915004),
 np.float64(2.8354059202992197),
 np.float64(4.451394259489213),
 np.float64(1.4983990472880828),
 np.float64(1.3523286458212818),
 np.float64(-4.72354575194098),
 np.float64(-1.5864511213623338),
 np.float64(3.2362538410893507),
 np.float64(-1.3333218275608925),
 np.float64(2.4791122015163474),
 np.float64(-2.882794054980187),
 np.float64(0.7384213318640107),
 np.float64(-2.5965047664713077),
 np.float64(2.03042571772413),
 np.float64(0.8195018867353632),
 np.float64(4.849276046401572),
 np.float64(4.779002281167921),
 np.float64(-1.9856013956225294),
 np.float64(0.7992751763200436),
 np.float64(1.7053299190166893),
 np.float64(0.8871418798500894),
 np.float64(5.26292673360663),
 np.float64(5.012582260547129),
 np.float64(-4.837849406937234),
 np.float64(-2

## Comparing numpy arrays to python lists

In [18]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]

x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.002838324s
normalize_py(list(float64)[50000]) -> total time: 0.027839752s


#### Python is slower than numpy in general

In [19]:
%%timeit

np.min(x)

32.9 µs ± 2.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%%timeit

min(y)

2.73 ms ± 416 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)


In [22]:
%%timeit

np.min(a)

5.44 µs ± 1.64 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [23]:
%%timeit

min(b)

1.66 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [24]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [28]:
x = np.random.rand(1000, 20000)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(1000, 20000)) -> total time: 0.189661978s
normalize_np_(ndarray(1000, 20000)) -> total time: 0.139641280s
